# Generated by Django 5.0.7 on 2024-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('Abaya', 'Abaya'), ('Planner', 'Planner')], default='Abaya', max_length=15),
        ),
    ]
